import 'package:flutter/foundation.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:twozerofoureight/domain/core/logic/action_runner/action_runner.dart';
import 'package:twozerofoureight/domain/core/logic/board_actors/merge_actor.dart';
import 'package:twozerofoureight/domain/core/logic/board_actors/slide_actor.dart';
import 'package:twozerofoureight/domain/core/logic/board_direction.dart';
import 'package:twozerofoureight/domain/puzzle/models/block/block.dart';
import 'package:twozerofoureight/domain/puzzle/models/board/board.dart';
import 'package:twozerofoureight/domain/puzzle/value_objects/block_point.dart';
import 'package:twozerofoureight/domain/puzzle/value_objects/board_size.dart';
import 'package:twozerofoureight/helpers/list_extensions.dart';

void main() {
  group("Merge actor test => ", () {
    test("should return board without modification if board is invalid", () {
      final board = Board(blocks: [
        Block.random(index: 3, boardSize: 3),
        Block.random(index: 4, boardSize: 3),
        Block.random(index: 5, boardSize: 3),
        Block.random(index: 6, boardSize: 3),
        Block.random(index: 7, boardSize: 3),
        Block.random(index: 8, boardSize: 3),
      ]);

      expect(
          ActionRunner(MergeActor(board, direction: BoardDirection.left()))
              .run(),
          equals(board));
    });
    group("Merged block modification test => ", () {
      void testMergeBoard(
          {@required int no,
          @required BoardSize boardSize,
          @required BoardDirection direction,
          @required List<BlockPoint> points,
          @required List<BlockPoint> expectedPoints}) {
        test(
            'should return merged board in $direction for board pattern no: $no',
            () {
          if (points.length != boardSize.totalSize ||
              expectedPoints.length != boardSize.totalSize) {
            expect(true, false);
            return;
          }
          final blocks = List.generate(boardSize.totalSize, (index) {
            return Block.empty(index: index, boardSize: boardSize.value)
                .copyWith(point: points[index]);
          });
          final board = Board(blocks: blocks);
          final expectedBlocks = List.generate(boardSize.totalSize, (index) {
            return Block.empty(index: index, boardSize: boardSize.value)
                .copyWith(point: expectedPoints[index]);
          });
          final expectedBoard = Board(blocks: expectedBlocks);
          final mergedBoard =
              ActionRunner(SlideActor(board, direction: direction))
                  .chain((slidedBoard) {
            return MergeActor(slidedBoard, direction: direction);
          }).run();

          mergedBoard.blocks.indexedMap((index, mergedBlock) {
            final expectedBlock = expectedBoard.blocks[index];
            expect(mergedBlock.index, equals(expectedBlock.index));
            expect(mergedBlock.point, equals(expectedBlock.point));
          });
        });
      }

      group("For board size 3 => ", () {
        final boardSize = BoardSize(3);
        group("For left direction", () {
          final direction = BoardDirection.left();
          testMergeBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            expectedPoints: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty
            ],
          );
          testMergeBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two
            ],
            expectedPoints: [
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty
            ],
          );
          testMergeBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four
            ],
            expectedPoints: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty
            ],
          );
          testMergeBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
            ],
            expectedPoints: [
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four
            ],
          );
          testMergeBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            expectedPoints: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
          );
        });
        group("for right direction => ", () {
          final direction = BoardDirection.right();
          testMergeBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two
            ],
          );
          testMergeBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four
            ],
          );
          testMergeBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four
            ],
          );
          testMergeBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four
            ],
          );
          testMergeBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            expectedPoints: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
          );
        });

        group("For up direction => ", () {
          final direction = BoardDirection.up();
          testMergeBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two
            ],
            expectedPoints: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
          );
          testMergeBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
          );
          testMergeBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
            ],
            expectedPoints: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
          );
          testMergeBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four
            ],
            expectedPoints: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty
            ],
          );
          testMergeBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four.mergedPoint()
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four.mergedPoint()
            ],
          );
        });

        group("for down direction => ", () {
          final direction = BoardDirection.down();
          testMergeBoard(
              no: 1,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
              ]);
          testMergeBoard(
              no: 2,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four
              ]);
          testMergeBoard(
              no: 3,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
              ]);
          testMergeBoard(
              no: 4,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two
              ]);
          testMergeBoard(
              no: 5,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two
              ]);
        });
      });
      group("for board size 4 => ", () {
        final boardSize = BoardSize(4);
        group("for left direction => ", () {
          final direction = BoardDirection.left();
          testMergeBoard(
              no: 1,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty
              ],
              expectedPoints: [
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 2,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 3,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 4,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty
            ],
            expectedPoints: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
          );
          testMergeBoard(
              no: 6,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four
              ],
              expectedPoints: [
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 7,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty
              ]);
          testMergeBoard(
              no: 8,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four
              ],
              expectedPoints: [
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
            no: 9,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint()
            ],
            expectedPoints: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
            ],
          );
          testMergeBoard(
              no: 10,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint().mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty
              ],
              expectedPoints: [
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four.mergedPoint().mergedPoint(),
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint().mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
        });
        group("for right direction => ", () {
          final direction = BoardDirection.right();
          testMergeBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
            ],
          );
          testMergeBoard(
              no: 2,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
              ]);
          testMergeBoard(
              no: 3,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 4,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
              ]);
          testMergeBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
            ],
          );
          testMergeBoard(
            no: 6,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
            ],
          );
          testMergeBoard(
            no: 7,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
            ],
          );
          testMergeBoard(
            no: 8,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
            ],
          );
          testMergeBoard(
            no: 9,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.four,
            ],
          );
          testMergeBoard(
            no: 10,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
          );
        });
        group("for up direction => ", () {
          final direction = BoardDirection.up();
          testMergeBoard(
              no: 1,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
              ],
              expectedPoints: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 2,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 3,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 4,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 5,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
              ],
              expectedPoints: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 6,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 7,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
              ],
              expectedPoints: [
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 8,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 9,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
              ],
              expectedPoints: [
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
          testMergeBoard(
              no: 10,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four.mergedPoint().mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint(),
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.four.mergedPoint(),
                BlockPoint.four.mergedPoint().mergedPoint(),
                BlockPoint.four.mergedPoint(),
                BlockPoint.empty,
                BlockPoint.four.mergedPoint().mergedPoint(),
                BlockPoint.empty,
                BlockPoint.empty,
              ]);
        });
        group("for down direction => ", () {
          final direction = BoardDirection.down();
          testMergeBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
          );
          testMergeBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
            ],
          );
          testMergeBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
            ],
          );
          testMergeBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
            ],
          );
          testMergeBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
          );
          testMergeBoard(
            no: 6,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
            ],
          );
          testMergeBoard(
              no: 7,
              boardSize: boardSize,
              direction: direction,
              points: [
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.empty,
                BlockPoint.two,
                BlockPoint.two,
                BlockPoint.two,
              ],
              expectedPoints: [
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four,
                BlockPoint.empty,
                BlockPoint.empty,
                BlockPoint.four.mergedPoint(),
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.two,
                BlockPoint.four,
                BlockPoint.four,
                BlockPoint.four,
              ]);
          testMergeBoard(
            no: 8,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
          );
          testMergeBoard(
            no: 9,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
          );
          testMergeBoard(
            no: 10,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            expectedPoints: [
              BlockPoint.empty,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
          );
        });
      });
    });
  });
}
