import 'package:flutter/foundation.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:twozerofoureight/domain/core/logic/action_runner/action_runner.dart';
import 'package:twozerofoureight/domain/core/logic/board_actors/slide_actor.dart';
import 'package:twozerofoureight/domain/core/logic/board_direction.dart';
import 'package:twozerofoureight/domain/puzzle/models/block/block.dart';
import 'package:twozerofoureight/domain/puzzle/models/board/board.dart';
import 'package:twozerofoureight/domain/puzzle/value_objects/block_point.dart';
import 'package:twozerofoureight/domain/puzzle/value_objects/board_size.dart';
import 'package:twozerofoureight/helpers/list_extensions.dart';

void main() {
  group("Slide actor test => ", () {
    test("should return board without modification if board is invalid", () {
      final board = Board(blocks: [
        Block.random(index: 3, boardSize: 3),
        Block.random(index: 4, boardSize: 3),
        Block.random(index: 5, boardSize: 3),
        Block.random(index: 6, boardSize: 3),
        Block.random(index: 7, boardSize: 3),
        Block.random(index: 8, boardSize: 3),
      ]);

      expect(
          ActionRunner(SlideActor(board, direction: BoardDirection.left()))
              .run(),
          equals(board));
    });
    group("slided block modification test => ", () {
      void testSlideBoard({
        @required int no,
        @required BoardSize boardSize,
        @required BoardDirection direction,
        @required List<BlockPoint> points,
        @required List<int> detachIndexes,
      }) {
        test(
            'should return slided board in $direction for board pattern no: $no',
            () {
          if (points.length != boardSize.totalSize ||
              detachIndexes.length != boardSize.totalSize) {
            expect(true, false);
            return;
          }
          final blocks = List.generate(boardSize.totalSize, (index) {
            return Block.empty(index: index, boardSize: boardSize.value)
                .copyWith(point: points[index]);
          });
          final slidedBlocks = blocks.indexedMap((index, block) {
            return block.detach(detachIndexes[index]);
          });
          final board = Board(blocks: blocks);
          final slidedBoard = Board(blocks: slidedBlocks);
          final expectedBoard =
              ActionRunner(SlideActor(board, direction: direction)).run();

          expect(expectedBoard, slidedBoard);
        });
      }

      group("For board size 3 => ", () {
        final boardSize = BoardSize(3);
        group("for left direction => ", () {
          final direction = BoardDirection.left();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [0, 1, 0, 3, 3, 5, 6, 7, 8],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [0, 0, 0, 3, 3, 5, 6, 6, 7],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four
            ],
            detachIndexes: [0, 0, 1, 3, 4, 5, 6, 6, 7],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
            ],
            detachIndexes: [0, 1, 1, 3, 4, 3, 6, 7, 8],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [0, 1, 2, 3, 4, 5, 6, 7, 8],
          );
        });

        group("for right direction => ", () {
          final direction = BoardDirection.right();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [2, 1, 2, 3, 5, 5, 6, 7, 8],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [2, 2, 2, 3, 5, 5, 7, 8, 8],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [1, 2, 2, 3, 4, 5, 7, 8, 8],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four
            ],
            detachIndexes: [1, 1, 2, 5, 4, 5, 6, 7, 8],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [0, 1, 2, 3, 4, 5, 6, 7, 8],
          );
        });

        group("For up direction => ", () {
          final direction = BoardDirection.up();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two
            ],
            detachIndexes: [0, 1, 2, 3, 1, 5, 6, 7, 2],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two
            ],
            detachIndexes: [0, 1, 2, 0, 1, 2, 3, 7, 2],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four
            ],
            detachIndexes: [0, 1, 2, 0, 4, 2, 3, 7, 5],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four
            ],
            detachIndexes: [0, 1, 2, 3, 4, 5, 6, 1, 5],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four.mergedPoint()
            ],
            detachIndexes: [0, 1, 2, 3, 4, 5, 6, 7, 8],
          );
        });

        group("for down direction => ", () {
          final direction = BoardDirection.down();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [0, 1, 8, 3, 7, 5, 6, 7, 8],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty
            ],
            detachIndexes: [3, 1, 8, 6, 7, 8, 6, 7, 8],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty
            ],
            detachIndexes: [3, 1, 5, 6, 4, 8, 6, 7, 8],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two
            ],
            detachIndexes: [0, 7, 5, 3, 4, 5, 6, 7, 8],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two
            ],
            detachIndexes: [0, 1, 2, 3, 4, 5, 6, 7, 8],
          );
        });
      });

      group("for board size 4 => ", () {
        final boardSize = BoardSize(4);
        group("for left direction => ", () {
          final direction = BoardDirection.left();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [
              0,
              1,
              2,
              0,
              4,
              5,
              4,
              7,
              8,
              8,
              10,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty
            ],
            detachIndexes: [
              0,
              1,
              0,
              0,
              4,
              4,
              6,
              4,
              8,
              9,
              10,
              8,
              12,
              12,
              12,
              15
            ],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [0, 1, 0, 3, 4, 4, 6, 7, 8, 8, 8, 9, 12, 13, 14, 15],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two
            ],
            detachIndexes: [
              0,
              1,
              0,
              1,
              4,
              4,
              6,
              5,
              8,
              8,
              9,
              11,
              12,
              12,
              13,
              13
            ],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty
            ],
            detachIndexes: [
              0,
              1,
              0,
              1,
              4,
              4,
              6,
              5,
              8,
              9,
              10,
              9,
              12,
              12,
              13,
              15
            ],
          );
          testSlideBoard(
            no: 6,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four
            ],
            detachIndexes: [0, 1, 1, 3, 4, 5, 6, 7, 8, 8, 8, 9, 12, 13, 12, 13],
          );
          testSlideBoard(
            no: 7,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four
            ],
            detachIndexes: [
              0,
              0,
              2,
              1,
              4,
              4,
              5,
              7,
              8,
              8,
              9,
              10,
              12,
              12,
              13,
              13
            ],
          );
          testSlideBoard(
            no: 8,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four
            ],
            detachIndexes: [
              0,
              1,
              2,
              1,
              4,
              5,
              5,
              7,
              8,
              9,
              9,
              10,
              12,
              12,
              13,
              13
            ],
          );
          testSlideBoard(
            no: 9,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint()
            ],
            detachIndexes: [
              0,
              0,
              1,
              2,
              4,
              5,
              5,
              6,
              8,
              9,
              10,
              10,
              12,
              12,
              13,
              14
            ],
          );
          testSlideBoard(
            no: 10,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty
            ],
            detachIndexes: [
              0,
              1,
              1,
              2,
              4,
              5,
              6,
              6,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15
            ],
          );
        });
        group("for right direction => ", () {
          final direction = BoardDirection.right();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
            ],
            detachIndexes: [
              3,
              1,
              2,
              3,
              4,
              7,
              6,
              7,
              8,
              9,
              11,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
            ],
            detachIndexes: [
              3,
              3,
              2,
              3,
              7,
              5,
              7,
              7,
              11,
              9,
              10,
              11,
              12,
              15,
              15,
              15
            ],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            detachIndexes: [
              0,
              3,
              2,
              3,
              4,
              5,
              7,
              7,
              10,
              11,
              11,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              2,
              3,
              2,
              3,
              6,
              5,
              7,
              7,
              8,
              10,
              11,
              11,
              14,
              14,
              15,
              15
            ],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
            ],
            detachIndexes: [
              2,
              3,
              2,
              3,
              6,
              5,
              7,
              7,
              10,
              9,
              10,
              11,
              12,
              14,
              15,
              15
            ],
          );
          testSlideBoard(
            no: 6,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
            ],
            detachIndexes: [
              0,
              2,
              2,
              3,
              4,
              5,
              6,
              7,
              10,
              11,
              11,
              11,
              14,
              15,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 7,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
            ],
            detachIndexes: [
              2,
              1,
              3,
              3,
              4,
              6,
              7,
              7,
              9,
              10,
              11,
              11,
              14,
              14,
              15,
              15
            ],
          );
          testSlideBoard(
            no: 8,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              2,
              1,
              2,
              3,
              4,
              6,
              6,
              7,
              9,
              10,
              10,
              11,
              14,
              14,
              15,
              15
            ],
          );
          testSlideBoard(
            no: 9,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              1,
              2,
              3,
              3,
              5,
              6,
              6,
              7,
              9,
              9,
              10,
              11,
              13,
              14,
              15,
              15
            ],
          );
          testSlideBoard(
            no: 10,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            detachIndexes: [
              1,
              2,
              2,
              3,
              5,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15
            ],
          );
        });
        group("for up direction => ", () {
          final direction = BoardDirection.up();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
            ],
            detachIndexes: [0, 1, 2, 3, 4, 1, 6, 7, 8, 9, 2, 11, 12, 13, 14, 3],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [0, 1, 2, 3, 0, 5, 2, 7, 0, 9, 10, 3, 12, 1, 2, 3],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            detachIndexes: [0, 1, 2, 3, 4, 1, 2, 7, 8, 1, 10, 3, 12, 5, 14, 15],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [0, 1, 2, 3, 0, 1, 2, 7, 4, 5, 10, 3, 4, 13, 6, 7],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
            ],
            detachIndexes: [0, 1, 2, 3, 0, 5, 2, 7, 4, 9, 10, 3, 12, 5, 6, 7],
          );
          testSlideBoard(
            no: 6,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            detachIndexes: [0, 1, 2, 3, 4, 1, 6, 7, 0, 1, 10, 7, 4, 5, 14, 15],
          );
          testSlideBoard(
            no: 7,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
            ],
            detachIndexes: [0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 11, 4, 9, 14, 7],
          );
          testSlideBoard(
            no: 8,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
            ],
            detachIndexes: [0, 1, 2, 3, 0, 5, 6, 7, 4, 5, 6, 11, 4, 9, 14, 7],
          );
          testSlideBoard(
            no: 9,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
            ],
            detachIndexes: [0, 1, 2, 3, 0, 5, 6, 3, 4, 9, 6, 7, 8, 9, 10, 11],
          );
          testSlideBoard(
            no: 10,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
            ],
            detachIndexes: [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              7,
              12,
              13,
              10,
              11
            ],
          );
        });
        group("for down direction => ", () {
          final direction = BoardDirection.down();
          testSlideBoard(
            no: 1,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            detachIndexes: [
              0,
              1,
              2,
              15,
              4,
              5,
              14,
              7,
              8,
              13,
              10,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 2,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            detachIndexes: [
              0,
              13,
              14,
              15,
              12,
              5,
              6,
              15,
              12,
              9,
              14,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 3,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              0,
              9,
              2,
              3,
              4,
              13,
              6,
              15,
              8,
              13,
              14,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 4,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              8,
              1,
              10,
              11,
              8,
              9,
              6,
              15,
              12,
              13,
              14,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 5,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.empty,
            ],
            detachIndexes: [
              0,
              9,
              10,
              11,
              8,
              5,
              6,
              15,
              12,
              9,
              14,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 6,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              8,
              9,
              2,
              3,
              12,
              13,
              6,
              11,
              8,
              13,
              10,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 7,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              8,
              5,
              2,
              11,
              8,
              9,
              10,
              7,
              12,
              13,
              14,
              15,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 8,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              8,
              5,
              2,
              11,
              8,
              9,
              10,
              7,
              12,
              9,
              10,
              11,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 9,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.two,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.empty,
            ],
            detachIndexes: [
              4,
              5,
              6,
              7,
              8,
              5,
              10,
              11,
              12,
              9,
              10,
              15,
              12,
              13,
              14,
              15
            ],
          );
          testSlideBoard(
            no: 10,
            boardSize: boardSize,
            direction: direction,
            points: [
              BlockPoint.empty,
              BlockPoint.four.mergedPoint().mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.empty,
              BlockPoint.four.mergedPoint(),
              BlockPoint.four.mergedPoint(),
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.four,
              BlockPoint.empty,
              BlockPoint.two,
              BlockPoint.two,
              BlockPoint.two,
            ],
            detachIndexes: [
              0,
              1,
              6,
              7,
              4,
              5,
              6,
              11,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15
            ],
          );
        });
      });
    });
  });
}
